(define (is-valid-sudoku board)
    (define rows  (make-vector 9 0))
    (define cols  (make-vector 9 0))
    (define boxes (make-vector 9 0))
    (let/ec fail
        (for ([i (in-range 9)])
            (for ([j (in-range 9)])
                (define c (list-ref (list-ref board i) j))
                (unless (char=? c #\.)
                    (define v (- (char->integer c) (char->integer #\1))) ; 0..8
                    (define mask (arithmetic-shift 1 v))
                    (define b (+ (* (quotient i 3) 3) (quotient j 3)))
                    (when (or (not (zero? (bitwise-and (vector-ref rows i) mask)))
                              (not (zero? (bitwise-and (vector-ref cols j) mask)))
                              (not (zero? (bitwise-and (vector-ref boxes b) mask))))
                        (fail #f))
                    (vector-set! rows i  (bitwise-ior (vector-ref rows i) mask))
                    (vector-set! cols j  (bitwise-ior (vector-ref cols j) mask))
                    (vector-set! boxes b (bitwise-ior (vector-ref boxes b) mask)))))
        #t)) 